### ISSUE TITLE
Adding Data Science Resources

### ISSUE THREAD

**Issue by Soumya007-developer** [ieeessitvit/Machine-learning#24]
Can we add data science resources(Beginner to advanced level)? @sumanth19k @IEEE-SSIT

**Comment by ssitvit** [comment]
yes you can
We will be creating a repo especially for data science.

**Comment by ssitvit** [comment]
@Soumya007-developer Follow https://github.com/ieeessitvit/Data-Science to contribute to our repo. Thank you.
